### ISSUE TITLE
Model time

### ISSUE THREAD

**Issue by AngelaKTE** [TokenEngineeringCommunity/BalancerPools_Model#11]
- how to implement "time" in our simulation, state update functions

- *requirements:*
- input: time needs to be parsed from input data sets 
- is input parameter to customize observation time
- is output parameter for data frames/plots
- is output parameter for min/max comparison
- (anything missing?)

options/variants:
- blockno (various transactions in 1 block no)
- timestamp (derived from blockno)
- transaction no (to derive blockno and timestamp)

**Comment by Ramarti** [comment]
- Each change (pool operation, price feed) will have a timestamp in the action json, field 'datetime'. This will be seen in simulation in the state variable `change_datetime` so time can be a common x axis for all plots
- Each change will be a timestep
