### ISSUE TITLE
Remove "spot price" calculation from V1.0 scripts

### ISSUE THREAD

**Issue by AngelaKTE** [TokenEngineeringCommunity/BalancerPools_Model#58]
- spot price calculation not required for analysis in V1.0
- spot price reference can vary case by case, we'll only need it for later version slippage analysis
- for V1.0 remove spot_prices from the data frame
- setting spot price reference not required, initial value spot prices not required (genesis_states.py)

**Comment by Ramarti** [comment]
option added to include or not spot prices in post processing method.
