### ISSUE TITLE
Exit fee

### ISSUE THREAD

**Issue by AngelaKTE** [TokenEngineeringCommunity/BalancerPools_Model#7]
- implement exit fee in our model (phase 1)?
- documentation: "All Balancer Protocol smart contracts were coded supporting a protocol-level exit fee to be charged that goes to Balancer Labs for supporting the development of the protocol. However, after careful consideration the Balancer Labs team decided to launch the first version of Balancer without any protocol fees whatsoever. (For technical reasons, this is unlikely to change.)  

https://docs.balancer.finance/core-concepts/protocol/index

**Comment by VasilySumanov** [comment]
For some financial products (automated portfolios, indexes, etc) exit fee is the key part of the business model. For example indices like PowerPool

**Comment by Ramarti** [comment]
Exit fees are included in model policies but set to 0 in Balancer Constants
