### ISSUE TITLE
token_(symbol)_weights to normalized weights

### ISSUE THREAD

**Issue by AngelaKTE** [TokenEngineeringCommunity/BalancerPools_Model#77]
Refactor "token_(symbol)_weight" to normalized weights:

[The white paper](https://balancer.finance/whitepaper/#value-function) defines it in terms of the normalized weights (such that the sum of all normalized weights is 1) - so 0.8 and 0.2 in that case.

As for the why, it's not explicitly stated in the white paper, but from [eq 10 in this proof](https://balancer.finance/whitepaper/#constant-value-distribution-proof) we see that Wn must be a number between 0 and 1 (since 0<Vn<V by definition).

_Originally posted by @markusbkoch in https://github.com/TokenEngineeringCommunity/BalancerPools_Model/issues/45#issuecomment-792732438_

**Comment by Ramarti** [comment]
So i add token_(symbol)_denorm and token_(symbol)_weight from 0 to 1

**Comment by AngelaKTE** [comment]
Wait - no  need to touch token_(symbol)_**denorm**.

Just change **token_(symbol)_weight** as outlined (0 to 1).

**Comment by Ramarti** [comment]
Done
